Get running under Play 2.2.
Testing just CAS authentication, Errors occur from upstream after CAS redirects back to the application.  This appears to be induced by the changes in the Play results structure.

java.lang.NoSuchMethodError: org.pac4j.play.CallbackController.redirect(Ljava/lang/String;)Lplay/mvc/Result;